# Use the other image as base
FROM ghcr.io/p-miranda/docker-test:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script and requirements file into the container
COPY program/app2.py .

# Command to run the Python script
CMD ["python", "app2.py"]
